/** @type {import('tailwindcss').Config} */
// Tokens ported verbatim from the Stitch export (code.html:11-107), with one
// correction: DESIGN.md specifies an 8px default radius; code.html shipped 0.25rem.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-charcoal': '#1B1E2B',
        primary: '#fff8ed',
        secondary: '#c6c6c7',
        'tertiary-fixed': '#6af6ff',
        'surface-container': '#1d1f29',
        'void-black': '#0F111A',
        'on-tertiary-container': '#006c71',
        'primary-fixed': '#ffe25f',
        'on-error': '#690005',
        'electric-gold': '#FFDB17',
        'on-primary': '#3a3000',
        tertiary: '#e6feff',
        surface: '#11131c',
        'surface-container-high': '#282933',
        'on-background': '#e1e1ef',
        'on-tertiary-fixed': '#002022',
        'secondary-fixed': '#e2e2e2',
        'inverse-primary': '#6e5d00',
        'hyper-pink': '#FF3278',
        'surface-tint': '#e6c500',
        'on-surface-variant': '#cfc6ab',
        error: '#ffb4ab',
        'secondary-container': '#454747',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#534600',
        'secondary-fixed-dim': '#c6c6c7',
        'error-container': '#93000a',
        'on-surface': '#e1e1ef',
        'surface-bright': '#373943',
        'on-secondary': '#2f3131',
        'surface-dim': '#11131c',
        'on-tertiary': '#003739',
        'inverse-on-surface': '#2e303a',
        'inverse-surface': '#e1e1ef',
        outline: '#989078',
        'on-secondary-fixed': '#1a1c1c',
        'tertiary-fixed-dim': '#00dce6',
        'on-primary-fixed': '#221b00',
        background: '#11131c',
        'primary-fixed-dim': '#e6c500',
        'outline-variant': '#4c4732',
        'surface-container-low': '#191b24',
        'primary-container': '#ffdb17',
        'on-tertiary-fixed-variant': '#004f53',
        'intensity-red': '#F06055',
        'surface-container-highest': '#32343e',
        'surface-container-lowest': '#0c0e17',
        'on-secondary-fixed-variant': '#454747',
        'tertiary-container': '#05f4ff',
        'surface-variant': '#32343e',
        'on-primary-container': '#716000',
        'on-secondary-container': '#b4b5b5',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '48px',
        'section-gap': '120px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-xl': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-xl': ['80px', { lineHeight: '88px', letterSpacing: '-0.04em', fontWeight: '900' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        // Admin-density additions (see plan: type scale compresses for tables)
        'table-cell': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
